server:
  port: 19999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yixiao_blog?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: shujinghuan
  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
